version: '3'

services:
    db:
        image: 'mysql:latest'
        platform: linux/amd64
        environment:
            - 'MYSQL_ROOT_PASSWORD=toor'
            - 'MYSQL_DATABASE=petanque'
            - 'MYSQL_USER=petanque'
            - 'MYSQL_PASSWORD=petanque'
        ports:
            - '3306:3306'
        volumes:
            - db-data:/var/lib/mysql:rw
        networks:
            - petanque

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8081:80'
        depends_on:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: toor
        networks:
            - petanque

    www:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www
            - vendor:/var/www/vendor
        networks:
            - petanque

    node:
        image: node:lts-alpine
        working_dir: /var/www
        volumes:
            - ./:/var/www
        tty: true
        networks:
            - petanque

networks:
    petanque:
        driver: bridge

volumes:
    db-data:
    vendor:
